### ISSUE TITLE
migrate the master to main branch

### ISSUE THREAD

**Issue by gaborbernat** [pypa/build#220]
I think we should migrate from using the master branch to main, per https://github.com/github/renaming#renaming-the-default-branch-from-master. @FFY00 can you go ahead with this? (I think currently only you have such rights).

**Comment by FFY00** [comment]
That is fine, we just need to make sure it does not cause any breakage (I don't think it will).

**Comment by gaborbernat** [comment]
Here you go https://github.com/pypa/build/tree/main 👍🏻 if you can.

**Comment by gaborbernat** [comment]
Ping on this @FFY00

**Comment by FFY00** [comment]
Sorry for the delay. As soon as we clean up the current (active) PRs, I will rename.

**Comment by FFY00** [comment]
Done, everything should be sorted out now :blush: 
Sorry for the delay.

**Comment by The-Compiler** [comment]
This seems to break old links. For example, with https://github.com/pypa/build/blob/master/CHANGELOG.rst (which I had in a script generating [GitHub comments](https://github.com/qutebrowser/qutebrowser/pull/6191#issue-577303964)) now shows me an outdated changelog.

GItHub claims to redirect those links properly, so maybe this breaks because the [`master` branch still exists](https://github.com/pypa/build/branches)?

**Comment by gaborbernat** [comment]
@FFY00 can you delete master?

**Comment by FFY00** [comment]
Sorry for the delay, done.

**Comment by FFY00** [comment]
Verified and the link redirection should be working now :+1:

**Comment by The-Compiler** [comment]
Looks good now, thanks! :+1:
